[project]
name = "camerasystem-endpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-cors>=5.0.0",
    "flask-socketio>=5.5.1",
    "flask>=3.1.0",
    "opencv-python>=4.10.0.84",
    "picamera2>=0.3.25",
]
