[project]
name = "camerasystem-endpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "opencv-python>=4.10.0.84",
]
